apiVersion: v2
name: atp3-playwright-runner
description: A Helm chart for deploying the atp3 playwright executor.
type: application
version: 2.0.1
appVersion: "1.0"
dependencies:
  - name: deployment-lib
    version: "0.0.1"
    repository: "file://../deployment-lib"